# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-06 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blockDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('previousHash', models.CharField(max_length=40)),
                ('currentBlock', models.CharField(max_length=40)),
                ('senderKey', models.CharField(max_length=50)),
                ('recieverKey', models.CharField(max_length=50)),
            ],
        ),
    ]
