# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-06 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0002_blockdb_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockdb',
            name='description',
            field=models.TextField(default='NO DESCRIPTION'),
        ),
    ]
