# Generated by Django 2.0.7 on 2018-07-06 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0003_auto_20180706_1639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blockdb',
            old_name='currentBlock',
            new_name='hashe',
        ),
        migrations.RenameField(
            model_name='blockdb',
            old_name='recieverKey',
            new_name='receiverKey',
        ),
        migrations.RemoveField(
            model_name='blockdb',
            name='description',
        ),
        migrations.AddField(
            model_name='blockdb',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
    ]
