# Generated by Django 2.0.7 on 2018-07-06 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0004_auto_20180706_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockdb',
            name='data',
            field=models.TextField(default=''),
        ),
    ]
