# Generated by Django 2.0.7 on 2018-07-07 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0005_auto_20180706_2312'),
    ]

    operations = [
        migrations.CreateModel(
            name='testblockDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(default='')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('previousHash', models.CharField(max_length=40)),
                ('hashe', models.CharField(max_length=40)),
                ('senderKey', models.CharField(max_length=50)),
                ('receiverKey', models.CharField(max_length=50)),
                ('amount', models.FloatField(default=0.0)),
            ],
        ),
    ]
