# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-07 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0006_testblockdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='userFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastMod', models.DateTimeField(auto_now_add=True)),
                ('userid', models.CharField(max_length=50)),
                ('balance', models.FloatField(default=0.0)),
            ],
        ),
    ]
